apiVersion: v1
kind: Service
metadata:
  name: personal-portfolio-service
  namespace: personal-portfolio
spec:
  type: NodePort
  selector:
    app: personal-portfolio
  ports:
    - port: 80
      targetPort: 3000
